### ISSUE TITLE
Collaborating

### ISSUE THREAD

**Issue by hongooi73** [ijlyttle/AzureOAuth#2]
Hi @ijlyttle, I saw your comment over on the httr2 repo on device code authentication. I didn't realise that you were also working on Oauth tokens for Azure.

I've written a suite of packages for talking to Azure from R, which are now on CRAN. One of them in particular, [AzureRMR](https://github.com/cloudyr/AzureRMR), has functionality for obtaining tokens. I've now separated this out into its own package at https://github.com/cloudyr/AzureAuth, which should also be on CRAN in the near future.

Would you be interested in collaborating with me on this? There are still some features I'd like to add, such as dSTS and federated logins. Longer term, I'd like for AzureAuth to be like the R equivalent of the ADAL client libraries; I'm sure there's plenty of stuff I'm not even aware of yet.

**Comment by ijlyttle** [comment]
Hi @Hong-Revo,

Thanks for reaching out!

My work was done a couple of years ago, out of necessity, as I couldn't find anything else at the time that would work. I am glad that you (and Microsoft) are filling the gap.

One the one hand, I would be super-enthused to collaborate, especially because I could learn so much from you and your work. On the other hand, my focus at work has moved away from Azure (for now).

Certainly, you are welcome to repurpose any of the code - and I will do my best to answer any questions you may have about what I did. I am also happy to test things out. If acceptable to you, I would be happy to collaborate further, on the understanding I could reach a time limit very quickly (which I would tell you about).

Could that work for now?

Thanks!

**Comment by hongooi73** [comment]
No worries, will keep you in mind.
